<?php

use Illuminate\Database\Seeder;

class CropRecommendationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $crop = [
            'title' => 'کنجد',
            'has_clay' => true,
        ];
        $crop = \App\Crop::create($crop);
        $insert = [
            [
                "crop_id" => $crop->id,
                "kind" => "nitrogen",
                "from" => "0",
                "to" => "0.5",
                "value" => "350",
                "value_bio" => "300",
                "fee_bio" => 1,
                "bio_text" => "یک بسته ازتوبارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "nitrogen",
                "from" => "0.5",
                "to" => "1",
                "value" => "300",
                "value_bio" => "250",
                "fee_bio" => 1,
                "bio_text" => "یک بسته ازتوبارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "nitrogen",
                "from" => "1",
                "to" => "1.5",
                "value" => "250",
                "value_bio" => "200",
                "fee_bio" => 1,
                "bio_text" => "یک بسته ازتوبارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "nitrogen",
                "from" => "1.5",
                "to" => "20",
                "value" => "200",
                "value_bio" => "150",
                "fee_bio" => 1,
                "bio_text" => "یک بسته ازتوبارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "ph",
                "from" => "0",
                "to" => "6",
                "value" => "0",
                "value_bio" => "0",
                "fee_bio" => 0,
                "bio_text" => null,
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "ph",
                "from" => "6",
                "to" => "7",
                "value" => "100",
                "value_bio" => "100",
                "fee_bio" => 2,
                "bio_text" => "2 بسته تیوباسیلوس",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "ph",
                "from" => "7",
                "to" => "8",
                "value" => "200",
                "value_bio" => "200",
                "fee_bio" => 4,
                "bio_text" => "4 بسته تیوباسیلوس",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "ph",
                "from" => "8",
                "to" => null,
                "value" => "300",
                "value_bio" => "300",
                "fee_bio" => 6,
                "bio_text" => "6 بسته تیوباسیلوس",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "phosphorus",
                "from" => "0",
                "to" => "5",
                "value" => "150",
                "value_bio" => "75",
                "fee_bio" => 1,
                "bio_text" => "یک بسته فسفاته بارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "phosphorus",
                "from" => "5",
                "to" => "10",
                "value" => "100",
                "value_bio" => "50",
                "fee_bio" => 1,
                "bio_text" => "یک بسته فسفاته بارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "phosphorus",
                "from" => "10",
                "to" => "15",
                "value" => "50",
                "value_bio" => "25",
                "fee_bio" => 1,
                "bio_text" => "یک بسته فسفاته بارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "phosphorus",
                "from" => "15",
                "to" => "40",
                "value" => "0",
                "value_bio" => "0",
                "fee_bio" => 1,
                "bio_text" => "یک بسته فسفاته بارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "potash",
                "from" => "0",
                "to" => "150",
                "value" => "300",
                "value_bio" => "150",
                "fee_bio" => 1,
                "bio_text" => "یک بسته پتابارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "potash",
                "from" => "0",
                "to" => "150",
                "value" => "350",
                "value_bio" => "175",
                "fee_bio" => 1,
                "bio_text" => "یک بسته پتابارور",
                "clay" => "1",
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "potash",
                "from" => "150",
                "to" => "200",
                "value" => "200",
                "value_bio" => "100",
                "fee_bio" => 1,
                "bio_text" => "یک بسته پتابارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "potash",
                "from" => "150",
                "to" => "200",
                "value" => "300",
                "value_bio" => "150",
                "fee_bio" => 1,
                "bio_text" => "یک بسته پتابارور",
                "clay" => "1",
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "potash",
                "from" => "200",
                "to" => "250",
                "value" => "100",
                "value_bio" => "50",
                "fee_bio" => 1,
                "bio_text" => "یک بسته پتابارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "potash",
                "from" => "200",
                "to" => "250",
                "value" => "200",
                "value_bio" => "100",
                "fee_bio" => 1,
                "bio_text" => "یک بسته پتابارور",
                "clay" => "1",
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "potash",
                "from" => "250",
                "to" => "300",
                "value" => "50",
                "value_bio" => "25",
                "fee_bio" => 1,
                "bio_text" => "یک بسته پتابارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "potash",
                "from" => "250",
                "to" => "300",
                "value" => "100",
                "value_bio" => "50",
                "fee_bio" => 1,
                "bio_text" => "یک بسته پتابارور",
                "clay" => "1",
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "potash",
                "from" => "300",
                "to" => null,
                "value" => "0",
                "value_bio" => "0",
                "fee_bio" => 1,
                "bio_text" => "یک بسته پتابارور",
                "clay" => false,
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "potash",
                "from" => "300",
                "to" => "350",
                "value" => "50",
                "value_bio" => "25",
                "fee_bio" => 1,
                "bio_text" => "یک بسته پتابارور",
                "clay" => "1",
            ],
            [
                "crop_id" => $crop->id,
                "kind" => "potash",
                "from" => "350",
                "to" => null,
                "value" => "0",
                "value_bio" => "0",
                "fee_bio" => 1,
                "bio_text" => "یک بسته پتابارور",
                "clay" => "1",
            ],
        ];
        \App\Crop_recommendation::insert($insert);
    }
}
